# Generated by Django 3.0.1 on 2020-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200522_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregmodel',
            name='Gender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerregmodel',
            name='address',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerregmodel',
            name='email',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerregmodel',
            name='lastname',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerregmodel',
            name='password',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerregmodel',
            name='phone',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerregmodel',
            name='repass',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
